name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        lfs: true

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Cache Gradle dependencies
      uses: actions/cache@v3
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Build Backend
      run: ./gradlew build
      working-directory: .

    - name: Clean Remote Target (If Necessary)
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: 157.245.41.10
        username: ci-user
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          # Supprimer le répertoire app s'il existe
          sudo rm -rf /opt/greentrip/backend/app

    - name: Create Remote Directories
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: 157.245.41.10
        username: ci-user
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          # Créer les répertoires nécessaires
          sudo mkdir -p /opt/greentrip/backend/app/build/libs

    - name: Deploy Backend to Server
      uses: appleboy/scp-action@v0.1.7
      with:
        host: 157.245.41.10
        username: ci-user
        password: ${{ secrets.SERVER_PASSWORD }}
        source: app/build/libs/app-0.0.1.jar
        target: /opt/greentrip/backend/app/build/libs/
        tar: false  # Désactiver l'archivage tar

    - name: Restart Backend Container
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: 157.245.41.10
        username: ci-user
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          cd /opt/greentrip/backend
          docker-compose down
          docker-compose up -d --build
          docker update --restart unless-stopped greentrip
